apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: docker-ex
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/alanboaventura/docker-ex
    targetRevision: main
    path: manifests
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true