apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-ex
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docker-ex
  template:
    metadata:
      labels:
        app: docker-ex
    spec:
      containers:
        - name: docker-ex
          image: docker-ex:test
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9999